# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20160416_1417'),
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSTrail',
            fields=[
                ('trail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trails.Trail')),
                ('station_begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_begin', to='stations.Station')),
                ('station_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_end', to='stations.Station')),
            ],
            bases=('trails.trail',),
        ),
    ]
