# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_auto_20160416_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nstrail',
            name='station_begin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_begin', to='stations.Station'),
        ),
        migrations.AlterField(
            model_name='nstrail',
            name='station_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_end', to='stations.Station'),
        ),
    ]
