# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_auto_20160416_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='gpx_file',
            field=models.FileField(upload_to='gpx/'),
        ),
    ]
