# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_auto_20160416_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='distance',
            field=models.FloatField(blank=True, help_text='distance in m', null=True),
        ),
    ]
